http.port = 8081
hmsi.key = i*NaSNj_rxkPAH,#B^Caz?CSy@J#o+Hl1hNvXYXbu=mg9|L-@Lv:*=:58b8*J-v$
hmsi.salt = 1fh,d&pgH8}Sxm><,^+d>4%4O^QR]G35
hmsi.Partner_Name = TWEAG_OEMHMSI
hmsi.Client_Secret_Key = wr5otyi0kl563ZGXF1VMDTWVZ4MYALTMD9780uzd6upxuiwLXCG6SS
hmsi.Content = application/json
hmsi.Client_Id = O7FGAj1px2-j91paXCULN-LIPYZbbh5i-ft8jzXPPOJ