http.port = 8081
http.host = localhost
hmsi.secretKey = VWh0anJCZWhxWDFNYnNKQXNObUMwZz09
hmsi.iv = 1LLCyESRssvXXiX1
hmsi.source = hondatw
hmsi.correlationId = 71bc-c4e5-6017-9d55-7d5172
hmsi.environment = VHUAT
hmsi.Content = application/octet-stream
hmsi.svc_name = getEBCLimit



