http.port = 8081
http.host = localhost
hmsi.secretKey = VWh0anJCZWhxWDFNYnNKQXNObUMwZz09
hmsi.iv = 1LLCyESRssvXXiX1
hmsi.source = hondatw
hmsi.user_name = cflintegration
hmsi.environment = VHUAT
hmsi.Content = application/octet-stream
hmsi.password = sdfvklj40934tsdlvjk309sd
hmsi.svc_name = CREATELOAN