#%RAML 1.0 DataType 

type: object
properties:
  orderSummary:
    type: object
    properties:
      modelName:
        type: string
        example: "ww"
        required: false
      modelVariant:
        type: string
        example: "aa"
        required: false
      modelColour:
        type: string
        example: "red"
        required: false
      modelExShowroomPrice:
        type: number
        example: 1233
        required: false
      insurance:
        type: string
        example: "qq"
        required: false
      rto:
        type: string
        example: "qqq"
        required: false
      financerName:
        type: string
        example: "efrfrf"
        required: false
      dealerName:
        type: string
        example: "aa"
        required: false
      loanTenor:
        type: number
        example: 434
        required: false
      downloadPayment:
        type: string
        example: "wssw"
        required: false
      loanAmount:
        type: number
        example: 22
        required: false
      roi:
        type: number
        example: 23322
        required: false
      emi:
        type: number
        example: 232
        required: false
      processingFees:
        type: number
        example: 11
        required: false
  sanction:
    type: object
    properties:
      sanctionLoanAmount:
        type: number
        example: 12333
        required: false
      downPayment:
        type: number
        example: 123
        required: false
      roiSanction:
        type: number
        example: 12
        required: false
      onRoadPrice:
        type: number
        example: 1213
        required: false
      emiSanction:
        type: number
        example: 1212
        required: false
      tenure:
        type: number
        example: 121
        required: false

