#%RAML 1.0 Trait

responses: 
  400:
    description: 
    body: 
      application/json:
        example: !include errorExamples/400.json
  401:
    description: 
    body: 
      application/json:
        example: !include errorExamples/401.json
  403:
    description: 
    body: 
      application/json:
        example: !include errorExamples/403.json
  404:
    description: 
    body: 
      application/json:
        example: !include errorExamples/404.json
  405:
    description: 
    body: 
      application/json:
        example: !include errorExamples/405.json
  406:
    description: 
    body: 
      application/json:
          example: !include errorExamples/406.json
  407:
    description: 
    body: 
      application/json:
        example: !include errorExamples/407.json
  415:
    description: 
    body: 
      application/json:
        example: !include errorExamples/415.json     
  422:
    description: 
    body: 
      application/json:
        example: !include errorExamples/422.json   
  429:
    description: 
    body: 
      application/json:
        example: !include errorExamples/429.json      
  500:
    description: 
    body: 
      application/json:
        example: !include errorExamples/500.json   
  503:
    description: 
    body: 
      application/json:
        example: !include errorExamples/503.json
  504:
    description: 
    body: 
      application/json:
        example: !include errorExamples/504.json
            
